[digitalocean]
token = "dop_v1_0000000000000000000000000000000000000000000000000000000000000000"
destroy = true

[digitalocean.ssh]
port = 22
user = "root"

[digitalocean.ssh.key]
folder = ".ssh"
name = "executor"

[digitalocean.droplet]
name = "executor"
region = "nyc3"
size = "docker-20-04"
image = "ubuntu-22-04-x64"
tag = "executor"

[task]
label = "ping"