[project]
name = "dode"

[digitalocean]
token = "dop_v1_0000000000000000000000000000000000000000000000000000000000000000"
destroy = true

[digitalocean.ssh]
port = 22
user = "root"

[digitalocean.ssh.key]
folder = ".ssh"
name = "example"

[digitalocean.droplet]
name = "example"
region = "nyc3"
size = "s-1vcpu-1gb"
image = "ubuntu-22-04-x64"
tags = ["example"]
