project:
  name: example

digitalocean:
  token: dop_v1_0000000000000000000000000000000000000000000000000000000000000000
  destroy: true
  droplet:
    name: example
    region: nyc3
    size: s-1vcpu-1gb
    image: ubuntu-22-04-x64
  ssh:
    key:
      name: example
      folder: .ssh
    port: 22
    user: root
